Report schema state when test failed

diff --git a/charts/redpanda/templates/tests/test-schemaregistry-internal-tls-status.yaml b/charts/redpanda/templates/tests/test-schemaregistry-internal-tls-status.yaml
--- a/charts/redpanda/templates/tests/test-schemaregistry-internal-tls-status.yaml
+++ b/charts/redpanda/templates/tests/test-schemaregistry-internal-tls-status.yaml
@@ -60,6 +60,43 @@ spec:
 
           set -ex
 
+          trap reportSchema ERR
+
+          reportSchema () {
+            echo Retrieving schemas/types
+            schemaCurlIgnore https://{{ include "redpanda.internal.domain" . }}:{{ .Values.listeners.schemaRegistry.port }}/schemas/types
+            echo Retrieving schemas/ids/1
+            schemaCurlIgnore https://{{ include "redpanda.internal.domain" . }}:{{ .Values.listeners.schemaRegistry.port }}/schemas/ids/1
+            echo Retrieving subjects
+            schemaCurlIgnore https://{{ include "redpanda.internal.domain" . }}:{{ .Values.listeners.schemaRegistry.port }}/subjects
+            echo Retrieving subjects?deleted=true
+            schemaCurlIgnore https://{{ include "redpanda.internal.domain" . }}:{{ .Values.listeners.schemaRegistry.port }}/subjects?deleted=true
+            echo Retrieving subjects/sensor-value/versions
+            schemaCurlIgnore https://{{ include "redpanda.internal.domain" . }}:{{ .Values.listeners.schemaRegistry.port }}/subjects/sensor-value/versions
+            echo Retrieving subjects/sensor-value/versions?deleted=true
+            schemaCurlIgnore https://{{ include "redpanda.internal.domain" . }}:{{ .Values.listeners.schemaRegistry.port }}/subjects/sensor-value/versions?deleted=true
+            echo Retrieving subjects/sensor-value/versions/latest
+            schemaCurlIgnore https://{{ include "redpanda.internal.domain" . }}:{{ .Values.listeners.schemaRegistry.port }}/subjects/sensor-value/versions/latest
+            echo Retrieving subjects/sensor-value/versions/latest?deleted=true
+            schemaCurlIgnore https://{{ include "redpanda.internal.domain" . }}:{{ .Values.listeners.schemaRegistry.port }}/subjects/sensor-value/versions/latest?deleted=true
+            echo Retrieving subjects/sensor-value/versions/latest/schema
+            schemaCurlIgnore https://{{ include "redpanda.internal.domain" . }}:{{ .Values.listeners.schemaRegistry.port }}/subjects/sensor-value/versions/latest/schema
+            echo Retrieving subjects/sensor-value/versions/latest/schema?deleted=true
+            schemaCurlIgnore https://{{ include "redpanda.internal.domain" . }}:{{ .Values.listeners.schemaRegistry.port }}/subjects/sensor-value/versions/latest/schema?deleted=true
+            echo
+          }
+
+          schemaCurlIgnore () {
+            curl -vm3 -w "\n" --fail --retry "120" --retry-max-time "120" --retry-all-errors -o - \
+              {{- if or (include "sasl-enabled" .|fromJson).bool .Values.listeners.schemaRegistry.authenticationMethod }}
+              -u "${RPK_USER}:${RPK_PASS}" \
+              {{- end }}
+              {{- if $cert.caEnabled }}
+              --cacert /etc/tls/certs/{{ $service.tls.cert }}/ca.crt \
+              {{- end }}
+              $* || true
+          }
+
           schemaCurl () {
             curl -svm3 --fail --retry "120" --retry-max-time "120" --retry-all-errors -o - \
               {{- if or (include "sasl-enabled" .|fromJson).bool .Values.listeners.schemaRegistry.authenticationMethod }}
diff --git a/charts/redpanda/templates/tests/test-schemaregistry-status.yaml b/charts/redpanda/templates/tests/test-schemaregistry-status.yaml
--- a/charts/redpanda/templates/tests/test-schemaregistry-status.yaml
+++ b/charts/redpanda/templates/tests/test-schemaregistry-status.yaml
@@ -55,6 +55,42 @@ spec:
           if [[ -n "$old_setting" ]]; then set -x; fi
   {{- end }}
 
+          set -e
+
+          trap reportSchema ERR
+
+          reportSchema () {
+            echo Retrieving schemas/types
+            schemaCurlIgnore http://{{ include "redpanda.internal.domain" . }}:{{ .Values.listeners.schemaRegistry.port }}/schemas/types
+            echo Retrieving schemas/ids/1
+            schemaCurlIgnore http://{{ include "redpanda.internal.domain" . }}:{{ .Values.listeners.schemaRegistry.port }}/schemas/ids/1
+            echo Retrieving subjects
+            schemaCurlIgnore http://{{ include "redpanda.internal.domain" . }}:{{ .Values.listeners.schemaRegistry.port }}/subjects
+            echo Retrieving subjects?deleted=true
+            schemaCurlIgnore http://{{ include "redpanda.internal.domain" . }}:{{ .Values.listeners.schemaRegistry.port }}/subjects?deleted=true
+            echo Retrieving subjects/sensor-value/versions
+            schemaCurlIgnore http://{{ include "redpanda.internal.domain" . }}:{{ .Values.listeners.schemaRegistry.port }}/subjects/sensor-value/versions
+            echo Retrieving subjects/sensor-value/versions?deleted=true
+            schemaCurlIgnore http://{{ include "redpanda.internal.domain" . }}:{{ .Values.listeners.schemaRegistry.port }}/subjects/sensor-value/versions?deleted=true
+            echo Retrieving subjects/sensor-value/versions/latest
+            schemaCurlIgnore http://{{ include "redpanda.internal.domain" . }}:{{ .Values.listeners.schemaRegistry.port }}/subjects/sensor-value/versions/latest
+            echo Retrieving subjects/sensor-value/versions/latest?deleted=true
+            schemaCurlIgnore http://{{ include "redpanda.internal.domain" . }}:{{ .Values.listeners.schemaRegistry.port }}/subjects/sensor-value/versions/latest?deleted=true
+            echo Retrieving subjects/sensor-value/versions/latest/schema
+            schemaCurlIgnore http://{{ include "redpanda.internal.domain" . }}:{{ .Values.listeners.schemaRegistry.port }}/subjects/sensor-value/versions/latest/schema
+            echo Retrieving subjects/sensor-value/versions/latest/schema?deleted=true
+            schemaCurlIgnore http://{{ include "redpanda.internal.domain" . }}:{{ .Values.listeners.schemaRegistry.port }}/subjects/sensor-value/versions/latest/schema?deleted=true
+            echo
+          }
+
+          schemaCurlIgnore () {
+            curl -vm3 --fail --retry "120" --retry-max-time "120" --retry-all-errors -o - \
+              {{- if or (include "sasl-enabled" .|fromJson).bool .Values.listeners.schemaRegistry.authenticationMethod }}
+              -u "${RPK_USER}:${RPK_PASS}" \
+              {{- end }}
+              $* || true
+          }
+
           schemaCurl () {
             curl -svm3 --fail --retry "120" --retry-max-time "120" --retry-all-errors \
             {{- if or (include "sasl-enabled" .|fromJson).bool .Values.listeners.schemaRegistry.authenticationMethod }}
