chore: create sts init container for fs validation

diff --git a/charts/redpanda/templates/secrets.yaml b/charts/redpanda/templates/secrets.yaml
--- a/charts/redpanda/templates/secrets.yaml
+++ b/charts/redpanda/templates/secrets.yaml
@@ -352,3 +352,57 @@ stringData:
     rpk --config "$CONFIG" redpanda config set redpanda.rack "${RACK}"
       {{- end }}
     {{- end }}
+{{- if .Values.statefulset.initContainers.fsValidator.enabled}}
+---
+apiVersion: v1
+kind: Secret
+metadata:
+  name: {{ (include "redpanda.fullname" .) | trunc 49 }}-fs-validator
+  namespace: {{ .Release.Namespace | quote }}
+  labels:
+  {{- with include "full.labels" . }}
+  {{- . | nindent 4 }}
+  {{- end }}
+type: Opaque
+stringData:
+  fsValidator.sh: |-
+    set -e
+    EXPECTED_FS_TYPE=$1
+
+    DATA_DIR="/var/lib/redpanda/data"
+    TEST_FILE="testfile"
+    
+    echo "checking data directory exist..."
+    if [ ! -d "${DATA_DIR}" ]; then
+      echo "data directory does not exists, exiting"
+      exit 1
+    fi
+    
+    echo "checking filesystem type..."
+    FS_TYPE=$(df -T $DATA_DIR  | tail -n +2 | awk '{print $2}')
+    
+    if [ "${FS_TYPE}" != "${EXPECTED_FS_TYPE}" ]; then
+      echo "file system found to be ${FS_TYPE} when expected ${EXPECTED_FS_TYPE}"
+      exit 1
+    fi
+    
+    echo "checking if able to create a test file..."
+    
+    touch ${DATA_DIR}/${TEST_FILE}
+    result=$(touch ${DATA_DIR}/${TEST_FILE} 2> /dev/null; echo $?)
+    if [ "${result}" != "0" ]; then
+      echo "could not write testfile, may not have write permission"
+      exit 1
+    fi
+    
+    echo "checking if able to delete a test file..."
+    
+    result=$(rm ${DATA_DIR}/${TEST_FILE} 2> /dev/null; echo $?)
+    if [ "${result}" != "0" ]; then
+      echo "could not delete testfile"
+      exit 1
+    fi
+    
+    echo "passed"
+
+{{- end }}
